apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  logging.pattern.console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  spring.cloud.gateway.mvc.routes[0].id: "employee"
  spring.cloud.gateway.mvc.routes[0].uri: "lb://employee"
  spring.cloud.gateway.mvc.routes[0].predicates[0]: "Path=/employee/**"
  spring.cloud.gateway.mvc.routes[1].id: "department"
  spring.cloud.gateway.mvc.routes[1].uri: "lb://department"
  spring.cloud.gateway.mvc.routes[1].predicates[0]: "Path=/department/**"
  spring.cloud.gateway.mvc.routes[2].id: "organization"
  spring.cloud.gateway.mvc.routes[2].uri: "lb://organization"
  spring.cloud.gateway.mvc.routes[2].predicates[0]: "Path=/organization/**"
  springdoc.swagger-ui.urls[0].name: "employee"
  springdoc.swagger-ui.urls[0].url: "/employee/v3/api-docs"
  springdoc.swagger-ui.urls[1].name: "department"
  springdoc.swagger-ui.urls[1].url: "/department/v3/api-docs"
  springdoc.swagger-ui.urls[2].name: "organization"
  springdoc.swagger-ui.urls[2].url: "/organization/v3/api-docs"
  spring.output.ansi.enabled: "ALWAYS"
  management.endpoints.web.exposure.include: "health,info,metrics,prometheus"
  management.metrics.enable.all: "true"
  management.metrics.distribution.percentiles-histogram.http.server.requests: "true"
  management.metrics.distribution.slo.http.server.requests: "1ms,5ms"