spring:
  application:
    name: gateway
  config:
    import: "optional:kubernetes:"
  cloud:
    kubernetes:
      config:
        enabled: true
      discovery:
        all-namespaces: true

springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /employee/v3/api-docs
      - name: department
        url: /department/v3/api-docs
      - name: organization
        url: /organization/v3/api-docs
