spring:
  application:
    name: organization
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        enabled: true
      discovery:
        all-namespaces: true
      secrets:
        enabled: true
        paths:
          - /etc/secretspot
